import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import Navbar from "@/components/navbar"
import Provider from "@/components/Provider"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Redisegn AI',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
        <Navbar />
        {children}
        </Provider>
      </body>
    </html>
  )
}
