import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import Provider from "@/components/Provider"
import ToasterProvider from '@/components/ToasterProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Redisegn AI',
  description: 'Generated by Ramadanyosi',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider />
        <Provider>
        {children}
        </Provider>
      </body>
    </html>
  )
}
